//! Regression tests for the rail record format.
//!
//! The canonical encoding is the load-bearing artifact: every signature and
//! every anchor stands on it, and an accidental byte-layout change would
//! invalidate five years of records. So these tests pin it three ways —
//! a golden digest, mutation sensitivity, and JSON round-trip parity.

use afterswap_rail::{
    AttestKey, AuditRecord, EvaluatedVenue, FillRef, QuoteEvidence, RailError, RouteDecision,
    VenueQuote, ZERO_HASH, attest, content_digest, link, merkle_proof, merkle_root, merkle_verify,
    record_hash, rule_v1_fingerprint, verify_attestation, verify_chain, verify_record,
};
use sha2::{Digest as _, Sha256};

const SEED: [u8; 32] = [7; 32];

/// Standard-alphabet base64 encode, test-side counterpart of the crate's
/// decoder.
fn b64(data: &[u8]) -> String {
    const A: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::new();
    for chunk in data.chunks(3) {
        let b = [chunk[0], *chunk.get(1).unwrap_or(&0), *chunk.get(2).unwrap_or(&0)];
        let n = (u32::from(b[0]) << 16) | (u32::from(b[1]) << 8) | u32::from(b[2]);
        out.push(A[(n >> 18) as usize & 63] as char);
        out.push(A[(n >> 12) as usize & 63] as char);
        out.push(match chunk.len() {
            1 => '=',
            _ => A[(n >> 6) as usize & 63] as char,
        });
        out.push(match chunk.len() {
            3 => A[n as usize & 63] as char,
            _ => '=',
        });
    }
    out
}

fn observed(body: &[u8]) -> QuoteEvidence {
    QuoteEvidence::Observed {
        body_b64: b64(body),
        body_sha256: Sha256::digest(body).into(),
    }
}

/// A fixed, fully-populated record: every field exercised, every value
/// deterministic.
fn fixture() -> AuditRecord {
    AuditRecord {
        seq: 42,
        prev_hash: [3; 32],
        t_ms: 1_787_000_000_000,
        instrument: "SOL/USDC".into(),
        quotes: vec![
            VenueQuote {
                venue: "dflow".into(),
                context_slot: Some(442_154_000),
                latency_us: 4_200,
                in_mint: "So11111111111111111111111111111111111111112".into(),
                out_mint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v".into(),
                in_amount: "1000000000".into(),
                out_amount: "108036854".into(),
                route: "Tessera V|1".into(),
                evidence: QuoteEvidence::ProviderSigned {
                    sig_headers: "signature-input: sig1=(\"@status\" \"content-digest\")".into(),
                    body_sha256: [9; 32],
                },
            },
            VenueQuote {
                venue: "jupiter".into(),
                context_slot: Some(442_154_002),
                latency_us: 6_100,
                in_mint: "So11111111111111111111111111111111111111112".into(),
                out_mint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v".into(),
                in_amount: "1000000000".into(),
                out_amount: "108031000".into(),
                route: "Whirlpool|2".into(),
                evidence: observed(br#"{"outAmount":"108031000","contextSlot":442154002}"#),
            },
        ],
        policy_fingerprint: rule_v1_fingerprint(),
        decision: RouteDecision {
            chosen_venue: "dflow".into(),
            evaluated: vec![
                EvaluatedVenue { venue: "dflow".into(), net_out: "108036854".into() },
                EvaluatedVenue { venue: "jupiter".into(), net_out: "108031000".into() },
            ],
        },
        fill: Some(FillRef {
            signature: "3zjjH2zPyhxGq5Fp1HYxsntKnpmrZfdwaRZoiKk5zHbF".into(),
            slot: 442_154_007,
            in_mint: "So11111111111111111111111111111111111111112".into(),
            out_mint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v".into(),
            in_amount: "1000000000".into(),
            out_amount: "108021500".into(),
            fee_lamports: 5_000,
        }),
        attestation: [0; 64],
    }
}

// -------------------------------------------------------------------------
// Canonical encoding
// -------------------------------------------------------------------------

/// Golden digest. Generated by this implementation, so it is a *change
/// detector*, not independent verification: if this fails, the byte layout
/// moved, and every existing signature and anchor is invalid. That is either
/// a release-noted schema-version bump or a bug — never a test to update
/// casually.
#[test]
fn canonical_digest_is_pinned() {
    let d = content_digest(&fixture());
    let hex: String = d.iter().map(|b| format!("{b:02x}")).collect();
    assert_eq!(hex, "49ceb0d4f1e7915efd9d1f218ac614f9417ffc36739c15320519c7225821c9a6");
}

type Mutation = Box<dyn Fn(&mut AuditRecord)>;

#[test]
fn every_field_reaches_the_digest() {
    let base = content_digest(&fixture());
    let mutations: Vec<Mutation> = vec![
        Box::new(|r| r.seq += 1),
        Box::new(|r| r.prev_hash[0] ^= 1),
        Box::new(|r| r.t_ms += 1),
        Box::new(|r| r.instrument.push('X')),
        Box::new(|r| r.quotes[0].out_amount = "108036855".into()),
        Box::new(|r| r.quotes[1].context_slot = None),
        Box::new(|r| r.quotes[1].latency_us += 1),
        Box::new(|r| {
            r.quotes[0].evidence = QuoteEvidence::ProviderSigned {
                sig_headers: "tampered".into(),
                body_sha256: [9; 32],
            }
        }),
        Box::new(|r| r.policy_fingerprint ^= 1),
        Box::new(|r| r.decision.chosen_venue = "jupiter".into()),
        Box::new(|r| r.decision.evaluated[1].net_out = "1".into()),
        Box::new(|r| r.fill = None),
        Box::new(|r| {
            if let Some(f) = &mut r.fill {
                f.fee_lamports += 1;
            }
        }),
    ];
    for (i, m) in mutations.iter().enumerate() {
        let mut r = fixture();
        m(&mut r);
        assert_ne!(content_digest(&r), base, "mutation {i} did not move the digest");
    }
}

/// The attestation is excluded from the content digest (a record cannot sign
/// its own signature) but included in the record hash (the chain commits to
/// records as published).
#[test]
fn attestation_is_outside_content_but_inside_record_hash() {
    let mut a = fixture();
    let mut b = fixture();
    a.attestation = [1; 64];
    b.attestation = [2; 64];
    assert_eq!(content_digest(&a), content_digest(&b));
    assert_ne!(record_hash(&a), record_hash(&b));
}

/// JSON is transport, canonical bytes are truth — but a record must survive
/// the trip between them with its digest intact, or a stored record could
/// not be re-verified.
#[test]
fn json_round_trip_preserves_the_digest() {
    let r = attest(fixture(), &AttestKey::from_seed(SEED));
    let json = serde_json::to_string(&r).expect("serialises");
    // Hashes travel as hex, not number arrays: auditors read these.
    assert!(json.contains("\"prev_hash\":\"0303"), "hex serialisation");
    let back: AuditRecord = serde_json::from_str(&json).expect("round trips");
    assert_eq!(back, r);
    assert_eq!(content_digest(&back), content_digest(&r));
    assert_eq!(record_hash(&back), record_hash(&r));
}

// -------------------------------------------------------------------------
// Attestation
// -------------------------------------------------------------------------

#[test]
fn attestation_signs_and_verifies() {
    let key = AttestKey::from_seed(SEED);
    let r = attest(fixture(), &key);
    assert!(verify_attestation(&r, &key.public()).is_ok());
}

#[test]
fn wrong_key_and_tampering_both_fail() {
    let key = AttestKey::from_seed(SEED);
    let other = AttestKey::from_seed([8; 32]);
    let r = attest(fixture(), &key);
    assert_eq!(verify_attestation(&r, &other.public()), Err(RailError::Attestation));
    let mut tampered = r.clone();
    tampered.t_ms += 1;
    assert_eq!(verify_attestation(&tampered, &key.public()), Err(RailError::Attestation));
}

/// Domain separation: a signature over the *raw* content digest — no domain
/// tag — must not verify as an attestation. This is the property that keeps
/// rail records uncollidable with anything else the key holder signs.
#[test]
fn a_signature_without_the_domain_tag_does_not_verify() {
    use ed25519_dalek::{Signer as _, SigningKey};
    let signing = SigningKey::from_bytes(&SEED);
    let mut r = fixture();
    let naked = signing.sign(&content_digest(&r));
    r.attestation = naked.to_bytes();
    let key = AttestKey::from_seed(SEED);
    assert_eq!(verify_attestation(&r, &key.public()), Err(RailError::Attestation));
}

// -------------------------------------------------------------------------
// Chain
// -------------------------------------------------------------------------

fn chain_of(n: u64) -> Vec<AuditRecord> {
    let key = AttestKey::from_seed(SEED);
    let mut out: Vec<AuditRecord> = Vec::new();
    for i in 0..n {
        let mut r = fixture();
        r.seq = i;
        let linked = link(r, out.last());
        out.push(attest(linked, &key));
    }
    out
}

#[test]
fn a_well_formed_chain_verifies_with_no_gaps() {
    let c = chain_of(4);
    assert_eq!(c[0].prev_hash, ZERO_HASH);
    let report = verify_chain(&c, None).expect("verifies");
    assert_eq!(report.records, 4);
    assert!(report.gaps.is_empty());
    assert_eq!(report.tip, record_hash(&c[3]));
}

#[test]
fn tampering_with_a_middle_record_breaks_the_chain_after_it() {
    let mut c = chain_of(4);
    c[1].t_ms += 1;
    let err = verify_chain(&c, None).expect_err("must break");
    // The record after the tampered one no longer links.
    assert_eq!(err, RailError::ChainLink(c[2].seq));
}

/// Gaps are reported, not rejected: a dropped cycle is a fact about capture
/// and hiding it would condition the log on success.
#[test]
fn seq_gaps_are_visible_but_valid() {
    let key = AttestKey::from_seed(SEED);
    let mut c = chain_of(2);
    let mut r = fixture();
    r.seq = 10; // gap: 1 -> 10
    let linked = link(r, c.last());
    c.push(attest(linked, &key));
    let report = verify_chain(&c, None).expect("gaps are not errors");
    assert_eq!(report.gaps, vec![(1, 10)]);
}

#[test]
fn non_monotonic_seq_is_rejected() {
    let mut c = chain_of(3);
    c[2].seq = c[1].seq; // equal is as bad as decreasing
    assert_eq!(verify_chain(&c, None), Err(RailError::SeqOrder(c[2].seq)));
}

#[test]
fn resuming_from_a_known_tip_checks_the_link() {
    let c = chain_of(4);
    let (head, tail) = c.split_at(2);
    let head_report = verify_chain(head, None).expect("head");
    assert!(verify_chain(tail, Some(head_report.tip)).is_ok());
    assert_eq!(
        verify_chain(tail, Some([5; 32])),
        Err(RailError::ChainLink(tail[0].seq))
    );
}

// -------------------------------------------------------------------------
// Merkle
// -------------------------------------------------------------------------

#[test]
fn every_leaf_proves_inclusion_at_many_sizes() {
    for n in [1usize, 2, 3, 4, 5, 7, 8, 33] {
        let leaves: Vec<[u8; 32]> = (0..n).map(|i| [i as u8; 32]).collect();
        let root = merkle_root(&leaves).expect("root");
        for (i, leaf) in leaves.iter().enumerate() {
            let proof = merkle_proof(&leaves, i).expect("proof");
            assert!(merkle_verify(leaf, &proof, &root), "n={n} i={i}");
        }
    }
}

#[test]
fn a_wrong_leaf_or_wrong_root_fails() {
    let leaves: Vec<[u8; 32]> = (0..5u8).map(|i| [i; 32]).collect();
    let root = merkle_root(&leaves).expect("root");
    let proof = merkle_proof(&leaves, 2).expect("proof");
    assert!(!merkle_verify(&[99; 32], &proof, &root));
    assert!(!merkle_verify(&leaves[2], &proof, &[0; 32]));
    // A proof for one index does not verify another leaf.
    assert!(!merkle_verify(&leaves[3], &proof, &root));
}

#[test]
fn empty_segments_have_no_root_and_bad_indices_are_refused() {
    assert_eq!(merkle_root(&[]), Err(RailError::Empty));
    let leaves = [[1u8; 32]];
    assert_eq!(merkle_proof(&leaves, 1), Err(RailError::MerkleIndex));
}

/// A leaf value must not be usable as an interior node (RFC 6962-style
/// domain separation): the root of [a, b] is not the plain hash of the two
/// leaf hashes without prefixes.
#[test]
fn leaf_and_node_domains_are_separated() {
    let leaves: Vec<[u8; 32]> = vec![[1; 32], [2; 32]];
    let root = merkle_root(&leaves).expect("root");
    let mut h = blake3::Hasher::new();
    h.update(&[1u8; 32]);
    h.update(&[2u8; 32]);
    assert_ne!(root, *h.finalize().as_bytes());
}

// -------------------------------------------------------------------------
// Standalone verification
// -------------------------------------------------------------------------

#[test]
fn a_valid_record_passes_full_verification() {
    let key = AttestKey::from_seed(SEED);
    let r = attest(fixture(), &key);
    assert!(verify_record(&r, &key.public()).is_ok());
}

#[test]
fn the_decision_must_reproduce_under_the_committed_rule() {
    let key = AttestKey::from_seed(SEED);
    let mut r = fixture();
    // Chosen venue is not the argmax: jupiter offered less.
    r.decision.chosen_venue = "jupiter".into();
    let r = attest(r, &key);
    match verify_record(&r, &key.public()) {
        Err(RailError::Decision(_, chose, should)) => {
            assert_eq!(chose, "jupiter");
            assert_eq!(should, "dflow");
        }
        other => panic!("expected Decision error, got {other:?}"),
    }
}

#[test]
fn an_unknown_rule_fingerprint_is_refused() {
    let key = AttestKey::from_seed(SEED);
    let mut r = fixture();
    r.policy_fingerprint = 0xDEAD_BEEF;
    let r = attest(r, &key);
    assert_eq!(
        verify_record(&r, &key.public()),
        Err(RailError::UnknownRule(0xDEAD_BEEF))
    );
}

#[test]
fn evaluated_venues_must_exist_in_the_quotes() {
    let key = AttestKey::from_seed(SEED);
    let mut r = fixture();
    r.decision.evaluated.push(EvaluatedVenue {
        venue: "phantom-venue".into(),
        net_out: "1".into(),
    });
    let r = attest(r, &key);
    assert_eq!(
        verify_record(&r, &key.public()),
        Err(RailError::UnknownVenue("phantom-venue".into()))
    );
}

#[test]
fn a_tampered_observed_body_fails_its_digest() {
    let key = AttestKey::from_seed(SEED);
    let mut r = fixture();
    if let QuoteEvidence::Observed { body_b64, .. } = &mut r.quotes[1].evidence {
        // Same length, different content — the digest is the only witness.
        *body_b64 = b64(br#"{"outAmount":"999999999","contextSlot":442154002}"#);
    }
    let r = attest(r, &key);
    assert_eq!(
        verify_record(&r, &key.public()),
        Err(RailError::Evidence("jupiter".into()))
    );
}

#[test]
fn amounts_must_be_bare_base10_integers() {
    let key = AttestKey::from_seed(SEED);
    for bad in ["1.5", "-3", "1e9", "", " 42", "0x10"] {
        let mut r = fixture();
        r.quotes[0].in_amount = bad.into();
        let r = attest(r, &key);
        assert_eq!(
            verify_record(&r, &key.public()),
            Err(RailError::Amount(bad.into())),
            "accepted {bad:?}"
        );
    }
}

/// The bug the browser verifier caught: a full-range u64 fingerprint crosses
/// JSON as a *string*, because JavaScript's number type mangles integers
/// above 2^53 on a parse→stringify round trip — which shifts the canonical
/// bytes and voids the attestation for any JS consumer.
#[test]
fn fingerprint_crosses_json_as_hex_and_survives_a_float_hostile_round_trip() {
    let key = AttestKey::from_seed(SEED);
    let r = attest(fixture(), &key);
    assert!(r.policy_fingerprint > 1 << 53, "fixture must exercise the range");
    let json = serde_json::to_string(&r).expect("serialises");
    assert!(
        json.contains(&format!("\"policy_fingerprint\":\"{:016x}\"", r.policy_fingerprint)),
        "fingerprint must be a hex string in JSON"
    );
    // A Value round trip (what any JSON tooling does) preserves the digest.
    let v: serde_json::Value = serde_json::from_str(&json).expect("value");
    let back: AuditRecord = serde_json::from_value(v).expect("back");
    assert_eq!(content_digest(&back), content_digest(&r));
    // Legacy records with numeric fingerprints still parse.
    let legacy = json.replace(
        &format!("\"policy_fingerprint\":\"{:016x}\"", r.policy_fingerprint),
        &format!("\"policy_fingerprint\":{}", r.policy_fingerprint),
    );
    let old: AuditRecord = serde_json::from_str(&legacy).expect("legacy parses");
    assert_eq!(old.policy_fingerprint, r.policy_fingerprint);
}

// -------------------------------------------------------------------------
// Archive framing
// -------------------------------------------------------------------------
//
// A closed segment is written to R2 as JSONL — the stored record bodies
// joined by `\n` — and the proof path rebuilds its Merkle leaves by splitting
// that object back apart and re-parsing each line. Once the SQLite rows have
// been trimmed, that read-back is the *only* copy, so the framing is
// load-bearing: these tests pin the round-trip and the one input that breaks
// it.

/// `n` distinct records, differing in the fields the segment index keys on.
fn segment(n: u64) -> Vec<AuditRecord> {
    (0..n)
        .map(|i| {
            let mut r = fixture();
            r.seq = 100 + i;
            r.t_ms += i * 250;
            r
        })
        .collect()
}

#[test]
fn an_archived_segment_rebuilds_identical_leaves_and_proofs() {
    let records = segment(9);
    let expected: Vec<[u8; 32]> = records.iter().map(record_hash).collect();
    let root = merkle_root(&expected).expect("root");

    // Close: bodies joined into one JSONL object, exactly as the worker writes.
    let bodies: Vec<String> = records
        .iter()
        .map(|r| serde_json::to_string(r).expect("compact"))
        .collect();
    let object = bodies.join("\n");

    // Read back: split and re-parse, exactly as the proof path does.
    let rebuilt: Vec<[u8; 32]> = object
        .split('\n')
        .map(|line| record_hash(&serde_json::from_str::<AuditRecord>(line).expect("archived line parses")))
        .collect();

    assert_eq!(rebuilt, expected, "read-back leaves must be byte-identical");
    assert_eq!(merkle_root(&rebuilt).expect("root"), root);
    for (i, leaf) in rebuilt.iter().enumerate() {
        let proof = merkle_proof(&rebuilt, i).expect("proof");
        assert!(merkle_verify(leaf, &proof, &root), "i={i}");
    }
}

/// Compact serialisation is what makes the framing safe: every string field
/// that could carry a newline is escaped, so a record is always one line.
#[test]
fn a_compact_record_never_contains_a_literal_newline() {
    let mut r = fixture();
    r.instrument = "SOL\n/USDC\r".into();
    let body = serde_json::to_string(&r).expect("compact");
    assert!(!body.contains('\n') && !body.contains('\r'));
    // The newline survives as an escape, so the value itself is preserved.
    assert_eq!(
        serde_json::from_str::<AuditRecord>(&body).expect("parses").instrument,
        r.instrument
    );
}

/// Why the worker rejects a body carrying a literal newline at ingest: such a
/// body parses and verifies exactly like a compact one, but shreds on
/// read-back — and by then the SQLite rows may be gone.
#[test]
fn a_pretty_printed_body_shreds_the_jsonl_framing() {
    let r = fixture();
    let pretty = serde_json::to_string_pretty(&r).expect("pretty");
    // Indistinguishable from compact JSON at ingest.
    assert_eq!(record_hash(&serde_json::from_str::<AuditRecord>(&pretty).expect("parses")), record_hash(&r));
    // But not a single line, so the archive splits it into unparseable pieces.
    assert!(pretty.contains('\n'));
    let fragments: Vec<&str> = pretty.split('\n').collect();
    assert!(fragments.len() > 1);
    assert!(
        fragments.iter().any(|f| serde_json::from_str::<AuditRecord>(f).is_err()),
        "a split pretty body must fail to re-parse"
    );
}
